[package]
name = "undisclosed_x86"
version = "0.1.0"
authors = ["rowlandsonpratt <striderman34@gmail.com>"]

[dependencies]
undisclosed_ir = { path = "../undisclosed_ir"}
undisclosed_util = { path = "../undisclosed_util"}